openapi: 3.0.1

info:
  title: IGPEC-APIVerificaPEC
  description: "API per **verificare** se una *casella di PEC* è correttamente funzionante. \n\n 
                Per *casella di PEC* correttamente funzionante si intende un indirizzo al quale il Gestore di competenza ha conferito tutte le abilitazioni necessarie per la completa operatività dello stesso."
  version: 1.0.0

servers:
- url: https://igpec.agid.gov.it/checkpec/rest/v1.0.0

security:
- app_id: []
- api_key: []

tags:
- name: base
- name: utility

paths:
  /{domain}/{localpart}:
    get:
      tags:
      - base
      description: Verifica lo stato del funzionamento di una PEC {localpart}@{domain}
      parameters:
      - name: domain
        in: path
        description: domain della PEC da verificare
        required: true
        schema:
          pattern: ^\w{1,}([\.-]{0,1}\w+){0,}(\.\w{2,})$
          type: string
      - name: localpart
        in: path
        description: localpart della PEC da verificare
        required: true
        schema:
          pattern: ^\w{1,}([\.-]?\w+){1,}$
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PECstatus'
        400:
          description: "BAD REQUEST: \n
                        - type: www.igpec.agid.gov.it/errorcode/badpath, title: errore del path, detail: path atteso /{domain}/{localpart}, status:400 \n
                        - type: www.igpec.agid.gov.it/errorcode/domain.pattern, title: errore nel {domain}, detail: {domain} pattern \\w{1,}([\\.-]{0,1}\\w+){0,}(\\.\\w{2,}), status:400 \n
                        - type: www.igpec.agid.gov.it/errorcode/localpart.pattern, title: errore nel {localpart}, detail: {localpart} pattern \\w{1,}([\\.-]?\\w+){1,}, status:400 "
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: "UNAUTHORIZED: \n
                        - type: www.igpec.agid.gov.it/errorcode/appid.notpresent, title: appid not present, detail: atteso header X-APP-ID, status:401 \n
                        - type: www.igpec.agid.gov.it/errorcode/apikey.notpresent, title: apikey not present, detail: atteso header X-API-KEY, status:401 \n
                        - type: www.igpec.agid.gov.it/errorcode/apikey.wrong, title: apikey errata, detail: apikey (header X-API-KEY) non corrisponde appid (header X-APP-ID), status:401"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: "NOT FOUND: \n
                        - type: www.igpec.agid.gov.it/errorcode/domain.notfound, title: {domain} not found, status:404 \n
                        - type: www.igpec.agid.gov.it/errorcode/localpart.notfound, title: {localpart} not found, status:404"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Gli HTTP state codes non indicati hanno un comportamento conforme alle indicazioni riportate in https://httpstatuses.com/
          content: {}

  /generate-apikey:
    put:
      tags:
      - utility
      description: Genera una nuova apikey
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiKey'
        400:
          description: "BAD REQUEST: \n
                        - type: www.igpec.agid.gov.it/errorcode/badpath, title: errore del path, detail: path atteso /generate-apikey, status:400"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: "UNAUTHORIZED: \n
                        - type: www.igpec.agid.gov.it/errorcode/appid.notpresent, title: appid not present, detail: atteso header X-APP-ID, status:401 \n
                        - type: www.igpec.agid.gov.it/errorcode/apikey.notpresent, title: apikey not present, detail: atteso header X-API-KEY, status:401 \n
                        - type: www.igpec.agid.gov.it/errorcode/apikey.wrong, title: apikey errata, detail: apikey (header X-API-KEY) non corrisponde appid (header X-APP-ID), status:401"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Gli HTTP state codes non indicati hanno un comportamento conforme alle indicazioni riportate in https://httpstatuses.com/
          content: {}

components:
  schemas:
    PECstatus:
      required:
      - email
      - esito
      - tipo
      type: object
      properties:
        email:
          type: string
          description: PEC {localpart}@{domain} di cui è stata richiesta la verifica dello stato di funzionamento
          format: email
        esito:
          type: string
          description: Stato di funzionamento della PEC
          enum:
          - OK
          - KO
        tipo:
          type: string
          description: Tipo della PEC verificato
          enum:
          - PA
          - Privato
      example:
        email: mailbox@pec.it
        esito: OK
        tipo: Privato

    ApiKey:
      required:
      - apiKey
      type: object
      properties:
        apiKey:
          type: string
          description: apikey generata
          format: uidd
      example:
        apikey: zaCELgL. 0imfnc8mVLWwsAawjYr4Rx-Af50DDqtlx

    Error:
      required:
      - status
      - title
      - type
      type: object
      properties:
        type:
          type: string
          description: uri che identifica il problema
          format: uri
        title:
          type: string
          description: Breve descrizione dello specifico problema verificatosi
        detail:
          type: string
          description: Descrizione di dettaglio dello specifico problema verificatosi
        status:
          maximum: 600
          minimum: 100
          type: integer
          description: HTTP status code generato dal server
          format: int32
      example:
        type: www.igpec.agid.gov.it/errorcode/badpath
        title: errore del path
        detail: path atteso /{domain}/{localpart}
        status: 400

  securitySchemes:
    api_key:
      type: apiKey
      description: HEADER utilizzato per indicare la apikey del client
      name: X-API-KEY
      in: header
    app_id:
      type: apiKey
      description: HEADER utilizzato per indicare l'identità del client
      name: X-APP-ID
      in: header
