swagger: "2.0"
info:
  description: "API per **verificare** se una *casella di PEC* è correttamente funzionante. \n\n
                Per *casella di PEC* correttamente funzionante si intende un indirizzo al quale il Gestore di competenza ha conferito tutte le abilitazioni necessarie per la completa operatività dello stesso."
            
  version: "1.0.0"
  title: "IGPEC-APIVerificaPEC"

host: "igpec.agid.gov.it"
basePath: "/cdpec/v1"

schemes:
- "https"

tags:
  - name: "base"
  - name: "utility"

paths:
  /{domain}/{localpart}:
    get:
      description: "Verifica lo stato del funzionamento di una PEC {localpart}@{domain} "      
      tags:
        - "base"
      produces:
      - "application/json"      
      parameters:
      - name: "domain"
        in: "path"
        description: "domain della PEC da verificare"
        required: true
        type: "string"
        pattern: '^\w{1,}([\.-]{0,1}\w+){0,}(\.\w{2,})$'
      - name: "localpart"
        in: "path"
        description: "localpart della PEC da verificare"
        required: true
        type: "string"
        pattern: '^\w{1,}([\.-]?\w+){1,}$'      
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Response"
        "400":
          description: "BAD REQUEST: \n
                        - code: 400.001, messaggage: path atteso /{domain}/{localpart} \n
                        - code: 400.002, messaggage: domain pattern \\w{1,}([\\.-]{0,1}\\w+){0,}(\\.\\w{2,})\n
                        - code: 400.003, messaggage: localpart patter \\w{1,}([\\.-]?\\w+){1,}                                    "
          schema:
            $ref: "#/definitions/Error"
        "401":
          description: "UNAUTHORIZED: \n
                        - code: 401.001, messaggage: appid not present \n
                        - code: 401.002, messaggage: apikey wrong"
          schema:
            $ref: "#/definitions/Error"
        "404":
          description: "NOT FOUND: \n
                        - code: 404.001, messaggage: {domain} not found \n
                        - code: 404.002, messaggage: {localpart} not found"
          schema:
            $ref: "#/definitions/Error"

        default:
            description: "Gli HTTP state codes non indicati hanno un comportamento conforme alle indicazioni riportate in https://httpstatuses.com/"
          
  /generate-apikey:
    put:
      description: "Genera una nuova apikey"
      tags:
        - "utility"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/ApiKey"            
        "400":
          description: "BAD REQUEST: \n
                        - code: 400.004, messaggage: path atteso /generate-apikey"
          schema:
            $ref: "#/definitions/Error"
        "401":
          description: |-
            UNAUTHORIZED:
            - code: 401.001, messaggage: appid not present
            - code: 401.002, messaggage: apikey wrong
          schema:
            $ref: "#/definitions/Error"

        default:
            description: "Gli HTTP state codes non indicati hanno un comportamento conforme alle indicazioni riportate in https://httpstatuses.com/"
 
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "X-API-KEY"
    in: "header"
    description: "HEADER utilizzato per indicare la apikey del client"
  app_id:
      type: "apiKey"
      name: "X-APP-ID"
      in: "header"
      description: "HEADER utilizzato per indicare l'identità del client"      

security:
        - app_id: []
        - api_key: []
    
definitions:
  Response:
    properties:
      email:
        description: "PEC di cui è stata richiesta la verifica dello stato di funzionamento"
        type: string
        format: email
      esito:
        description: "Stato di funzionamento della PEC"
        type: string
        enum: [OK, KO]
      tipo:
        description: "Tipo della PEC verificato"
        type: string
        enum: [PA, Privato]
    example: 
      email: "mailbox@pec.it"
      esito: "OK"
      tipo: "Privato"
    required:  
      - email
      - esito
      - tipo
      
  ApiKey:
    properties:
      apiKey: 
        description: "apikey generata"
        type: string
        format: uidd
    example: 
      apikey: "zaCELgL. 0imfnc8mVLWwsAawjYr4Rx-Af50DDqtlx"
    required:  
      - apiKey
  Error:
    properties:
      detail:
        description: |
          A human readable explanation specific to this occurrence of the
          problem. You MUST NOT expose internal informations, personal
          data or implementation details through this field.
        example: Request took too long to complete.
        type: string
      instance:
        description: |
          An absolute URI that identifies the specific occurrence of the problem.
          It may or may not yield further information if dereferenced.
        format: uri
        type: string
      status:
        description: |
          The HTTP status code generated by the origin server for this occurrence
          of the problem.
        example: 503
        exclusiveMaximum: true
        format: int32
        maximum: 600
        minimum: 100
        type: integer
      title:
        description: |
          A short, summary of the problem type. Written in english and readable
          for engineers (usually not suited for non technical stakeholders and
          not localized); example: Service Unavailable
        type: string
      type:
        default: about:blank
        description: |
          An absolute URI that identifies the problem type.  When dereferenced,
          it SHOULD provide human-readable documentation for the problem type
          (e.g., using HTML).
        example: https://tools.ietf.org/html/rfc7231#section-6.6.4
        format: uri
        type: string
    type: object
